#!/usr/bin/with-contenv bash

if [ ! -f /opt/ssh/sshd_config ];then
    echo "Copy sshd_config..."
    cp /tmp/sshd_config /opt/ssh/sshd_config
fi

if [ ! -f /opt/ssh/ssh_host_keys/ssh_host_ecdsa_key ];then
    echo "Generating ecdsa hostkey"
    ssh-keygen -q -N "" -t ecdsa -f /opt/ssh/ssh_host_keys/ssh_host_ecdsa_key
fi

if [ ! -f /opt/ssh/authorized_keys ];then
    echo "Generating public key"
    ssh-keygen -f /opt/ssh/ssh_host_keys/ssh_host_ecdsa_key -y > /opt/ssh/authorized_keys
fi